Draft
llmshare/llmproto pull request #2
Opened 2023-08-21 12:05 UTC by praetorian2710

The starting of the demo project

2023-08-22 09:12 UTC, Sing-Li requested changes
Commit early, commit often

Remember to push your daily work/exploration to this PR 

The title should also be changed to something more descriptive of what is contained.   Using *[Draft]*  as a prefix.

2023-08-24 00:40 UTC, Sing-Li reviewed
what version of nodejs are you using? I cannot get it to run.

2023-08-24 15:53 UTC, praetorian2710 commented
16.18.41,
but due to some problem in my machine, retejs officials told me to use codesandbox or codespaces, so i am coding in codesandbox.

2023-08-28 02:46 UTC, Sing-Li requested changes
it doesn't matter where or what you code in/with.

you need to commit only code that will run standalone.

you may want to check with others on setting up the program.

2023-08-28 07:15 UTC, praetorian2710 commented
Ok Im checking what is causing the issue

2023-08-28 09:56 UTC, Sing-Li requested changes
doesn't work at all.    try git cloning yourself into a brand new directory.

2023-08-28 09:59 UTC, praetorian2710 commented
Is it not working for node 20.5.1 and npm9.8.1?
I had to change my node and npm version, or else wasnt working

2023-08-28 10:10 UTC, praetorian2710 commented
cloned and checked https://github.com/praetorian2710/llmproto/tree/jotiraditya this.. worked perfectly fine

2023-09-08 19:16 UTC, Sing-Li commented
PoC completed.

2023-09-08 19:16 UTC, closed without merging