Auto code
llmshare/llmproto pull request #3
Opened 2023-08-21 20:56 UTC by Ashutosh0602

Working on a code generator using reteJS

2023-08-22 09:14 UTC, Sing-Li requested changes
Commit early, commit often

Try to push your daily exploration to the PR. 

Precede the title with *[Draft]*  to let maintainers know it is a work-in-progress and not to marge it.

2023-08-24 00:48 UTC, Sing-Li requested changes
won't start due to use of `console`

2023-08-28 02:51 UTC, Sing-Li requested changes
still doesn't run.   It appears to be just a sample from rete.

2023-08-28 06:56 UTC, Ashutosh0602 commented
Yes it is, because I am trying to solve the issue using AST so that's why I am learning again the dataflow of reteJS again. 

You can guide me whether I am going in right direction or not.

2023-08-28 09:59 UTC, Sing-Li requested changes
Use MVC as we've discussed in meeting.   Keep the model separate from rete  (the view).

2023-09-08 19:16 UTC, Sing-Li commented
PoC completed.

2023-09-08 19:16 UTC, closed without merging