[Draft]  Rete + Langchain Code Generator
llmshare/llmproto pull request #6
Opened 2023-08-29 20:54 UTC by spiritanand

Initial setup.

2023-08-31 16:24 UTC, Sing-Li requested changes
Looking good, especially the structure of the code that is taking shape!

![image](https://github.com/llmshare/llmproto/assets/122633/33426e95-6889-40d0-b6b7-2d987e58d07e)

Please commit frequently and commit early.   Use this draft as the backup storage for your daily work on this.   It will also keep me up to date with your progress.

I think creating a controller that has an action to "generate code" from the model would be a good piece to add.

2023-09-02 21:00 UTC, spiritanand commented
@Sing-Li I have created 2 separate models for `OpenAI` and the generated `Code`.

I have also added a (custom) button in the `CodeNode` which will help generate the required langchain code.

However, I have not yet added any controllers. Please LMK where I could add controllers in the app.


<img width="849" alt="image" src="https://github.com/llmshare/llmproto/assets/53999998/f2d69d84-e18b-4738-ab22-b963577eb75e">

2023-09-05 13:51 UTC, Sing-Li requested changes
Seems to be taking it in a different direction.   Please consider this:

Code ---> should not be an object in the app
Code --> is generated to a TEXT source file when the "generate" button is clicked
Code --> should never be part of the model
Model --> should contain many objects (collection of object instances)





Model --> should be backed by a database (you can use sqlite or other friendly Key-value alternatives)
Generate Button --> should not be part of the connectable blocks
Generate Button --> should be located around the frame of the entire page
Generate Button ---> when clicked should generate CODE = text file = from the diagram shown within the frame
Controller --> put all the code that will read the model (from the database) to generate the source text file there
Controller ---> has no link whatsoever to retejs

2023-09-05 14:43 UTC, spiritanand commented
@Sing-Li I have understood the part where we use a model (with a DB like SQLite or Postgres). I also understood the point regarding the code generation.

However, I could not understand,
Code ---> should not be an object in the app, and 
Code --> should never be part of the model

Also, could you point out the things I am doing right in this app, so I can know more about the direction.

2023-09-05 15:50 UTC, Sing-Li commented
> @Sing-Li I have understood the part where we use a model (with a DB like SQLite or Postgres). I also understood the point regarding the code generation.
> 
> However, I could not understand, Code ---> should not be an object in the app, and Code --> should never be part of the model
> 

The model contains the classes and instances that are in the code, and parameterization of their fields.

It lives only (single source of truth) in the database and nowhere else.

Code does not exist ANYWHERE until someone click the "Generate Code" button.    When that happens, your implementation (a method in the controller) should read the database to generate a text file -> the code.

> Do the above 2 points mean that I have to create `Code` (on the fly) for each request the user makes (click generate)?
> 

No.   Unless someone click that "Generate Code" button ON THE FRAME (not on each component), no code (text file) ever needs to be generated.

> Also, could you point out the things I am doing right in this app, so I can know more about the direction. Like the OpenAI model and OpenAINode. Are they right?, etc.

The way you depict a code element with a block -- that's correct.
The way you make the code flow connects with a socket and link --- that's correct.
The way you have separated model to be a class/directory on its own -- that's correct.

Those are 3 things heading in the right direction. @spiritanand

2023-09-05 15:56 UTC, Sing-Li commented
With the above understood.  It should be clear that the blocks in the diagram should contain:

loadSummarizationChain  at its heart, center.


And then all the parameterizations and preparation for  the chain (including other objects such as instance of RecursiveCharacterTextSplitter named textSplitter) feeding into it.

2023-09-05 16:04 UTC, spiritanand commented
Right @Sing-Li. Got that. Understood the part about code generation. I am confused in the sockets and connections. Do we want the connections (link and socket) to be made? Because currently, I am ignoring the connection and using the data directly from the model.

This means there will be multiple unconnected blocks like OpenAI, TextSplitter and others. They will directly feed into the options of loadSummarizartionChain through the model when we click on the generate button.

Here there is no need for connections since we already know all the imports being used. But I can understand if that will be required in future pages…

2023-09-05 16:06 UTC, spiritanand commented
> The _breakthrough_ in thinking required here is that parameters / arguments to a block are ALMOST ALWAYS not simple scalar/numbers like _temperature_ (integer), but most of the time will be complex classes and structure (or static JSON spec) itself.

Right regarding this, we will have to use something known as custom controls inside retejs. Create our custom input control and then use it in our nodes.

2023-09-05 16:08 UTC, Sing-Li commented
Totally agreed.   I don't have a strong opinion on that.

And if you do look around the web for code generators you'll see a diverse variety of way of handling that.

Of key here is certain "order of preparation" that are necessary, basically code generated that if they're out of order - will break.

This gets even more complex when one is generating code that is meant to be executed async (like NodeJS). 

Somehow, the graphical notation MUST allow the designer to specify that "order"  (perhaps via links, but I've see separate pages, or using an explict NUMBER prefix on each subflow)   so that the code generated will actually work.

Please let me know if you "get" the above.  Thanks.

2023-09-05 16:15 UTC, Sing-Li commented
For this initial commit, if you're not able to solve this tough _ordering problem_.   Its OK to just leave them as separate unconnected blocks.   Perhaps some "higher up" on the diagram than others.

2023-09-08 19:12 UTC, Sing-Li requested changes
![image](https://github.com/llmshare/llmproto/assets/122633/214907c8-e9e1-4775-8d20-4f70cfe4a2c1)

Good enough as proof-of-concept commit.    Closes #1

2023-09-08 19:13 UTC, Sing-Li approved these changes
![image](https://github.com/llmshare/llmproto/assets/122633/391adc2e-d364-4fdc-88e4-4ab20c296e89)

Good enough for PoC commit.

2023-09-08 19:15 UTC, merged